src/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get "/pages/donated", to: "pages#donated"

  # allow router to use the session controller, include facebook callback
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'} 

  devise_scope :user do
    get 'users/register', to: "users/sessions#register"
    get 'users/login', to: "users/sessions#login"

  end

  resources :listings 
  get "/:id/listings", to: "listings#user_listings", as: "user_listings" 

end

src/app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :condition
  has_and_belongs_to_many :categories
  has_one_attached :picture


 #default book image if not attached
 def picture_attachment_path
  picture.attached? ? picture : "book.png"
  end

  
end

src/app/controllers/listings_controller.rb
class ListingsController < ApplicationController

    before_action :authenticate_user!
    layout "listing"
    before_action :set_listing, only: [:edit, :update, :destroy]

    def index
        @listings = Listing.all
        @search = Listing.ransack(params[:q])
       @listings = @search.result(distinct: true)
    end

    def user_listings
        @listings = Listing.where("user_id = ?", params[:id]) 
    end

    def new
        set_categories_conditions
        @listing = Listing.new
    end

    def create        
        @listing = current_user.listings.create(listing_params)
       
        if @listing.errors.any? #if errors exist 
            set_categories_conditions
            render "new" #render the "new.html" view  
        else 
            # if no error redirect to the index page showing all listing
            flash[:notice] = "Listing created successfully!"
            redirect_to listings_path
        end
    end

    def edit
         set_categories_conditions
    end

    def update
        # save the object
        if @listing.update_attributes(listing_params)
            # if save succeeds redirect to the show section
            flash[:notice] = "Listing updated successfully."
            redirect_to listings_path
        else
        # if save fails, redisplay the form so user can fix problems
            render("edit")
        end
    end

    def destroy
        @listing.destroy
        flash[:notice] = "The listing '#{@listing.title}' deleted successfully."
        redirect_to(listings_path)
    end

    private

    def listing_params
        params.require(:listing).permit(:author, :title, :price, :condition_id, :note, :picture, :id, category_ids: [])  
    end

     #set values for dropdown menus/radio buttons
    def set_categories_conditions
        @categories =  Category.all
        @conditions = Condition.all
    end

    # pass id params into methods
    def set_listing
        @listing = Listing.find(params[:id])
    end
    

end

src/app/views/listings/_form.html.erb
<% if @listing.errors.any? %>
  <% @listing.errors.full_messages.each do |message| %>
    <li style="color: red"><%= message %></li>
  <% end %>
<% end %>
<%= form_with model: @listing, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :author%>
    <%= f.text_field :author, placeholder: "eg Charles Dickens", class: "form-control" %>
  </div>
  <fieldset class="group">
    <p>Select up to 3 categories</p>
    <ul class="checkbox">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
        <li><%= b.check_box %><%= b.label%></li>
      <%end%>
    </ul>
  </fieldset>
  <div class="form-group">
    <%= f.label :condition_id %>
    <%= f.select :condition_id, @conditions.map {|c| [c.state, c.id]}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control"%>
  </div>
  <div>
    <%= f.label :picture %>
    <%= f.file_field :picture,
   accept:'image/png, image/gif, image/jpeg, image/jpg' %>
    <% if @listing.errors.any? %>
      Not successful, please upload again.
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :anything_to_add_about_your_book? %>
    <%= f.text_area :note, class: "form-control text-muted"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-lg btn-primary btn-block"%>
  </div>
<% end %>

src/app/views/listings/_lists.html.erb
<div class="container mt-5">
  <h6 class="border-bottom border-gray pb-2 mb-0 text-center">Listings</h6>
  <% @listings.each do |listing| %>
    <div class="my-3 p-3 bg-white rounded shadow-sm booklists">
      <div class="pt-3 book-img-wrapper">
        <div class="book-img" >
          <%= image_tag listing.picture_attachment_path, class: "img-thumbnail"  %>
        </div>
      </div>
      <div class="pt-3 text-wrapper">
        <strong class="d-block text-gray-dark"> <%= listing.title%></strong>
        by <%= listing.author %> - <%= number_to_currency(listing.price)%> <br/>
        <%= fa_icon  "book"%>  <%= listing.categories.map(&:name).sort.join(", ")%><br/>
        Condition: <%= listing.condition.state %><br/>
        <%= listing.note %><br/>
        <% if current_user.id == listing.user_id %>
          <span><i>posted on </i><%=listing.created_at.strftime("%d-%m-%Y")%> by you</span><br/>
          <span class="icons-wrapper">
            <%= link_to edit_listing_path(listing) do %>
              <%= fa_icon "edit" %>
            <%end%>
            <%= link_to listing, method: :delete, class: "card-link",
              data: {confirm: "Are you sure you want to delete this listing?"}  do %>
              <%= fa_icon "trash" %>
            <%end%>
          </span>
        <%else%>
          <div class="post-by-date">
            <i>posted on </i><%=listing.created_at.strftime("%d-%m-%Y")%> by
            <%= listing.user.username%>
          </div>
          <div class="contact-btn">
            <button type="button" class="btn btn-secondary">Contact Seller</button>
            <%= get_picture(listing.user)%>
          </div>
        <% end%>
      </div>
    </div>
  <% end %>
</div>

src/app/views/listings/edit.html.erb
<div class="container">
  <div class="py-5 edit-listing">
    <h2 class="text-center">Edit a listing</h2>
    <%= render "form", listing: @listing%>
  </div>
</div>

src/app/views/listings/index.html.erb
<div class="container my-2 search">
  <!-- Search form -->
  <%= search_form_for @search do |f| %>
    <div class=" row search-wrapper">
      <div class="form-inline d-flex md-form form-lg col-md-8 active-cyan active-cyan-2">
        <div class="text-center">
          <%= fa_icon "search" %>
          <%= f.text_field :title_cont, class: "form-control form-control-lg ml-3", placeholder: "Search by book title" %>
        </div>
      </div>
      <div class="form-inline d-flex col-md-2 offset-md-2 clear-search-btn">
        <%= link_to "Clear search", listings_path, class:"actions btn"  %>
      </div>
    </div>
    <div class="card-header">
      Search by category
    </div>
    <div class="card-body">
      <ul class="checkbox">
        <%= f.collection_check_boxes :categories_id_in_any, Category.all, :id, :name do |b| %>
          <li><%= b.check_box %><%= b.label%></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-6 offset-md-3">
      <div class="text-center search-btn">
        <%= f.submit "Search", class:"actions btn"  %>
      </div>
    </div>
  <% end %>
</div>
<%= render "lists",  listings: @listings%>

src/app/views/listings/new.html.erb
<div class="container">
  <div class="back-button">
    <%= link_to listings_path do %>
      <div class="btn btn-light text-muted text-center">
        <%= fa_icon "chevron-left" %>
        <span>Back to listings</span>
      </div>
    <%end%>
  </div>
  <div class="py-5 create-listing">
    <h2 class="text-center">Create a listing</h2>
    <%= render "form", listing: @listing%>
  </div>
</div>

src/app/views/listings/user_listings.html.erb
<% if !@listings.exists? %>
  <h2 class="py-5 text-center">You have not listed any books yet. </h2>
<% else %>
  <%= render "lists", listings: @listings%>
<%end %>