src/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get "/pages/donated", to: "pages#donated"

  # allow router to use the session controller, include facebook callback
  devise_for :users, controllers: { 
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'} 

  devise_scope :user do
    get 'users/register', to: "users/sessions#register"
    get 'users/login', to: "users/sessions#login"

  end

  resources :listings 
  get "/:id/listings", to: "listings#user_listings", as: "user_listings" 

end

src/app/views/layouts/_navbar.html.erb
<div class="container" id="navbar">
  <header class="blog-header py-2 col-12-xs">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-md-5 py-1">
        <%= link_to "Buy", listings_path, class:"btn buy btn-light text-center"%>
        <%= link_to "Sell", new_listing_path,  class:"btn sell btn-light text-center"%>
        <% if user_signed_in? %>
          <%= link_to 'My listings', user_listings_path(current_user.id),  class:"btn listings btn-light text-center" %>
        <%end %>
      </div>
      <div class="col-md-2 text-center">
        <%= link_to root_path, :class => "blog-header-logo" do %>
          <div class="nav-bar-logo-img"> <%= image_tag "logo.png" %> </div>
        <%end%>
      </div>
      <div class="col-md-5 d-flex justify-content-end align-items-center">
        <% if user_signed_in? %>
          <span class="text-center mx-2">Hello, <%= current_user.username.partition(" ").first %></span>
          <span  class="nav-bar-profile-img">
            <%= get_picture(current_user) %>
          </span>
          <%= link_to 'Edit Profile',edit_user_registration_path, class:"btn edit btn-light text-center" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn logout btn-light text-center" %>
        <% else %>
          <%=  link_to "Log in", users_login_path, class:"btn btn btn-light text-muted"%>
          <%= link_to "Register", users_register_path, class:"btn btn-light text-muted text-center" %>
        <%end%>
      </div>
    </div>
  </header>
</div>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books Buzza</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="bg-light">
    <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>

src/app/views/layouts/listing.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>BooksBuzza</title>
  </head>
  <body class="bg-light">
    <%= render "layouts/navbar"%>
    <% if !flash[:notice].blank? %>
      <div class="notice text-center">
        <br>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>